openapi: "3.0.0"
info:
  title: Ecommerce delivery-Microservice
  version: 1.0.0
servers:
  - url: http://localhost:8082
    description: backend server

paths:
  /delivery/Addtodelivery:
    post:
      tags:
        - delivery
      summary: Add delivery to delivery
      requestBody:
        description: payload data
        content:
            application/json:
              schema:
                  $ref: "#/components/schemas/deliveryCreated"

      responses:
        "201":
          description: delivery added to delivery successfully
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/deliveryCreated"

  /deliverys/fetchdelivery:
    get:
      tags:
        - delivery
      summary: Fetch ALL delivery delivery
      requestBody:
        description: payload data
        content:
            application/json:
              schema:
                  $ref: "#/components/schemas/deliveryCreated"
      responses:
        "200":
          description: User created successfully
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/deliveryCreated"
  /deliverys/fetchOne:
    get:
      tags:
        - delivery
      summary: Fetch One delivery
      requestBody:
        description: payload data
        content:
            application/json:
              schema:
                  $ref: "#/components/schemas/deliveryCreated"
      responses:
        "200":
          description: User created successfully
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/deliveryCreated"
  /deliverys/Update:
    put:
      tags:
        - delivery
      summary: update delivery
      requestBody:
        description: payload data
        content:
            application/json:
              schema:
                  $ref: "#/components/schemas/deliveryCreated"
      responses:
        "200":
          description: User created successfully
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/deliveryCreated"

  /deliverys/delete:
    delete:
      tags:
        - delivery
      summary: update delivery
      requestBody:
        description: payload data
        content:
            application/json:
              schema:
                  $ref: "#/components/schemas/deliveryCreated"
      responses:
        "200":
          description: User created successfully
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/deliveryCreated"
   

  
components:
  schemas:
    deliveryCreated:
     type: object
     properties:
      title:
        type: string
      description:
        type: string
      manufacture_details:
        $ref: "#/components/schemas/manufacture_details"
      shipping_details:
        $ref: "#/components/schemas/shipping_details"
      quantity:
        type: number  
      pricing:
        type: object
        properties:
          price:
            type: number
       
      
    shipping_details:
      type: object
      properties:
        weight:
          type: number
        width:
          type: number
        height:
          type: number
        depth:
          type: number

      

    manufacture_details:
      type: object
      properties:
        model_number:
          type: string
        release_date:
          type: string
          format: date-time     
    users:
      type: object
      properties:
         name:
          type: string
         email:
          type: string
         address:
          $ref: "#/components/schemas/address"
         phone:
          type: string
         password:
          type: string
         role:
          type: string
          "enum": [ "user", "vendor","delivery","superAdmin","vendorManager","deliveryManager"]
      
            

   
    address:
      type: object
      properties:
        city:
            type: string
        region:
          type: string
        state:
          type: string
        country:
          type: string  
        zipCode:
          type: string
   
   
   
      
        