openapi: "3.0.0"
info:
  title: Ecommerce Products-Microservice
  version: 1.0.0
servers:
  - url: http://localhost:8082
    description: backend server

paths:
  /products/AddProduct:
    post:
      tags:
        - Product
      summary: Add new Product
      requestBody:
        description: payload data
        content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ProductCreated"

      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ProductCreated"

  /products/fetchAll:
    get:
      tags:
        - Product
      summary: Fetch ALL product
      requestBody:
        description: payload data
        content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ProductCreated"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ProductCreated"
  /products/fetchOne:
    get:
      tags:
        - Product
      summary: Fetch One product
      requestBody:
        description: payload data
        content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ProductCreated"
      responses:
        "200":
          description: User created successfully
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ProductCreated"
  /products/Update:
    put:
      tags:
        - Product
      summary: update product
      requestBody:
        description: payload data
        content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ProductCreated"
      responses:
        "200":
          description: User created successfully
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ProductCreated"

  /products/delete:
    delete:
      tags:
        - Product
      summary: update product
      requestBody:
        description: payload data
        content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ProductCreated"
      responses:
        "200":
          description: User created successfully
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ProductCreated"
   

  
components:
  schemas:
    ProductCreated:
     type: object
     properties:
      title:
        type: string
      description:
        type: string
      manufacture_details:
        $ref: "#/components/schemas/manufacture_details"
      shipping_details:
        $ref: "#/components/schemas/shipping_details"
      quantity:
        type: number  
      pricing:
        type: object
        properties:
          price:
            type: number
       
      
    shipping_details:
      type: object
      properties:
        weight:
          type: number
        width:
          type: number
        height:
          type: number
        depth:
          type: number

      

    manufacture_details:
      type: object
      properties:
        model_number:
          type: string
        release_date:
          type: string
          format: date-time     
    users:
      type: object
      properties:
         name:
          type: string
         email:
          type: string
         address:
          $ref: "#/components/schemas/address"
         phone:
          type: string
         password:
          type: string
         role:
          type: string
          "enum": [ "user", "vendor","delivery","superAdmin","vendorManager","deliveryManager"]
      
            

    posts:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        content:
          type: string
        user_id:
          type: string
        time_stamp:
          type: string
      
    address:
      type: object
      properties:
        city:
            type: string
        region:
          type: string
        state:
          type: string
        country:
          type: string  
        zipCode:
          type: string
    geo:
      type: object
      properties:
        lat:
          type: string
        lng:
          type: string
    company:
      type: object
      properties:
        CompanyName:
          type: string
        catchPhrase:
          type: string
        bs:
          type: string
    SignIn:
       type: object
       properties:
        email:
          type: string
        password::
          type: string
    Login:
      type: object
      properties:
        success:
          type: string
        message:
          type: string
        user:
          type: object
          properties:
            email:
              type: string
        token:
          type: string    
      
        